  publish:
    runs-on: ubuntu-latest
    needs: docker

    permissions:
      id-token: write
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build production image
        run: |
          docker build \
            --target production \
            -t ghcr.io/${{ github.repository_owner }}/bike-demand-ml:latest .

      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/bike-demand-ml:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::619071320026:role/bike-demand-ml
          aws-region: ap-south-1

      - name: Test AWS authentication
        run: |
          aws sts get-caller-identity